import { useState, useEffect } from 'react';
import { onValue, ref, db, importBackup, downloadBackup, update } from '../services/dataService';
import { useToast } from './ToastContext';
export default function AdminTools({tourConfig}) {
  const toast=useToast(),[audit,setAudit]=useState([]),[history,setHistory]=useState([]),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false);
  useEffect(()=>{const a=onValue(ref(db,'audit'),s=>setAudit(s.val()||[])),b=onValue(ref(db,'backupHistory'),s=>setHistory(s.val()||[]));return()=>{a();b();};},[]);
  const download=async(id)=>{try{const blob=await downloadBackup(id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`dpl-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);}catch(e){toast.error(e.message);}};
  return <section className="card mb24"><div className="card-header"><h3 className="text-accent">Điều lệ · Sao lưu · Nhật ký</h3></div>
    <div className="grid-2 mb16"><div><label className="form-label">Tích lũy vàng (trận khác nhau)<input className="input-dark" type="number" min="2" max="10" defaultValue={tourConfig.yellowThreshold||2} onBlur={async e=>{try{await update(ref(db,'tourConfig'),{yellowThreshold:Number(e.target.value)});toast.success('Đã lưu điều lệ.');}catch(err){toast.error(err.message);}}}/></label><label className="form-label"><input type="checkbox" checked={tourConfig.resetYellowsAtKnockout!==false} onChange={async e=>{try{await update(ref(db,'tourConfig'),{resetYellowsAtKnockout:e.target.checked});}catch(err){toast.error(err.message);}}}/> Tẩy tích lũy khi vào knockout (giữ án chưa chấp hành)</label><label className="form-label">Số lượt luân lưu đầu<select className="select-dark" value={tourConfig.shootoutRounds || 5} onChange={async e=>{try{await update(ref(db,'tourConfig'),{shootoutRounds:Number(e.target.value)});}catch(err){toast.error(err.message);}}}><option value="3">3 lượt</option><option value="5">5 lượt</option></select></label><label className="form-label">Thời lượng mỗi hiệp phụ (0 = vào luân lưu ngay)<input className="input-dark" type="number" min="0" max="30" defaultValue={tourConfig.extraTimeMinutes || 0} onBlur={async e=>{try{await update(ref(db,'tourConfig'),{extraTimeMinutes:Number(e.target.value)});}catch(err){toast.error(err.message);}}}/></label><label className="form-label">Nghỉ tối thiểu giữa hai trận (phút)<input className="input-dark" type="number" min="0" max="1440" defaultValue={tourConfig.minRestMinutes ?? 60} onBlur={async e=>{try{await update(ref(db,'tourConfig'),{minRestMinutes:Number(e.target.value)});}catch(err){toast.error(err.message);}}}/></label><p className="text-dim">Đỏ trực tiếp/vàng thứ hai: mặc định cấm 1 trận; BTC chọn số trận khi quyết định án. BXH ba đội dùng điểm, GD, GF bảng phụ rồi GD/GF toàn bảng.</p></div>
    <div><div className="flex-gap mb12"><button className="btn green" onClick={()=>download()}>Xuất database JSON</button><label className="btn ghost">Xem trước phục hồi<input type="file" accept=".json" hidden onChange={async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>15e6)throw new Error('File vượt 15 MB.');const data=JSON.parse(await file.text());if(data.schemaVersion!==2)throw new Error('Chỉ phục hồi backup schema 2.');setPreview(data);}catch(err){toast.error(err.message);}e.target.value='';}}/></label></div><p className="text-dim">Backup không chứa mật khẩu/tài khoản. Server giữ 5 bản tự động trước thay lịch hoặc phục hồi.</p>{preview&&<div className="qa-checklist"><b>Xem trước: {Object.keys(preview.matches||{}).length} trận · {Object.keys(preview.players||{}).length} đội</b><p className="text-gold">Dữ liệu giải hiện hành sẽ được thay thế sau khi kiểm tra toàn vẹn.</p><button className="btn danger" disabled={busy} onClick={async()=>{if(!window.confirm('Xác nhận phục hồi? Server sẽ sao lưu trạng thái hiện hành trước.'))return;setBusy(true);try{await importBackup(preview);setPreview(null);toast.success('Đã phục hồi và kiểm tra dữ liệu.');}catch(e){toast.error(e.message);}finally{setBusy(false);}}}>Xác nhận phục hồi</button><button className="btn ghost" onClick={()=>setPreview(null)}>Hủy</button></div>}{history.map(b=><button key={b.id} className="btn ghost tiny mb8" onClick={()=>download(b.id)}>{new Date(b.at).toLocaleString('vi-VN')} · {b.reason}</button>)}</div></div>
    <details><summary>Nhật ký tác nghiệp ({audit.length} thao tác gần nhất)</summary><div className="table-container"><table className="dpl-table"><thead><tr><th>Thời gian</th><th>Người dùng</th><th>Thao tác</th><th>Lý do</th></tr></thead><tbody>{audit.slice().reverse().slice(0,50).map(a=><tr key={a.id}><td>{new Date(a.at).toLocaleString('vi-VN')}</td><td>{a.by}</td><td>{a.kind} · {a.matchIds?.join(', ')}</td><td>{a.reason}</td></tr>)}</tbody></table></div></details>
  </section>;
}
