import { useEffect, useState } from 'react';
import { compressAvatarImage, rotateAvatarFile } from '../services/tournamentService';

export default function AvatarCropper(){
  const [request,setRequest]=useState(null),[x,setX]=useState(50),[y,setY]=useState(50),[zoom,setZoom]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const open=e=>{if(!e.detail.file||e.detail.file.size>12e6){e.detail.reject(new Error('Ảnh phải nhỏ hơn 12 MB.'));return;}setX(50);setY(50);setZoom(1);setError('');setRequest({...e.detail,url:URL.createObjectURL(e.detail.file)});};window.addEventListener('dpl-avatar-crop',open);return()=>window.removeEventListener('dpl-avatar-crop',open);},[]);
  useEffect(()=>{if(!request)return;return()=>URL.revokeObjectURL(request.url);},[request]);
  if(!request)return null;
  const cancel=()=>{request.reject(new Error('Đã hủy chọn ảnh.'));setRequest(null);};
  return <div className="modal-backdrop"><div className="modal-card" role="dialog" aria-modal="true" aria-label="Chỉnh ảnh cầu thủ" style={{maxWidth:460,padding:24}}><h3 className="text-accent mb12">Chỉnh ảnh đại diện</h3><p className="text-dim mb16">Ảnh vuông tối đa 180 px; nén JPEG. Chọn vị trí khuôn mặt trước khi lưu.</p><div style={{width:220,height:220,overflow:'hidden',margin:'auto',borderRadius:12,border:'1px solid var(--accent-green)'}}><img src={request.url} alt="Xem trước ảnh cầu thủ" style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:`${x}% ${y}%`,transform:`scale(${zoom})`,transformOrigin:`${x}% ${y}%`}} onError={()=>setError('Thiết bị không đọc được ảnh này. Hãy dùng JPG, PNG hoặc WebP.')}/></div><button className="btn ghost small mt12" disabled={busy} onClick={async()=>{setBusy(true);try{const file=await rotateAvatarFile(request.file);setRequest({...request,file,url:URL.createObjectURL(file)});setX(50);setY(50);setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}}>Xoay 90°</button><label className="form-label mt12">Vị trí ngang<input type="range" min="0" max="100" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label className="form-label">Vị trí dọc<input type="range" min="0" max="100" value={y} onChange={e=>setY(Number(e.target.value))}/></label><label className="form-label">Phóng to<input type="range" min="1" max="3" step="0.1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label>{error&&<p className="text-red" role="alert">{error}</p>}<div className="flex-gap mt16"><button className="btn green" disabled={busy||!!error} onClick={async()=>{setBusy(true);try{const data=await compressAvatarImage(request.file,180,.82,{x,y,zoom});request.resolve(data);setRequest(null);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'Đang nén…':'Dùng ảnh này'}</button><button className="btn ghost" data-modal-close onClick={cancel}>Hủy</button></div></div></div>;
}
